services:
    engagement-messenger:
      image: dylanlindgren/servicenow-em-client
      ports:
        - "${SN_EM_PORT}:80"
      volumes:
          - ./background.png:/usr/share/nginx/html/background.png
      environment:
          - MODULE_ID=${SN_EM_MODULE_ID}
          - INSTANCE_NAME=${SN_EM_INSTANCE_NAME}