services:
    engagement-messenger:
      image: dylanlindgren/servicenow-em-client
      ports:
        - "8084:80"
      volumes:
          - ./background.png:/usr/share/nginx/html/background.png
      environment:
          - MODULE_ID=60c794c3db862010b7c8dacbd39619fe
          - INSTANCE_NAME=dl3